# Generated by Django 4.2.3 on 2023-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_movie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
