# Generated by Django 4.2.3 on 2023-07-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_customer_options_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentorder',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
