# Generated by Django 4.2.3 on 2023-08-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history'), ('block_user', 'Can block customer')]},
        ),
    ]
